export { default as ChannelPressureGrid } from './components/ChannelPressureGrid.jsx'
export { default as ChokepointWatch } from './components/ChokepointWatch.jsx'
export { default as ConflictPanel } from './components/ConflictPanel.jsx'
export { default as ImpactSidebar } from './components/ImpactSidebar.jsx'
export { default as RippleBoard } from './components/RippleBoard.jsx'
export { defaultScenarioConfig } from './data/defaultScenario.js'
export { chokepoints, countries, focusModes } from './data/network.js'
export { useConflictScenario } from './hooks/useConflictScenario.js'
export { simulateConflict } from './lib/simulateConflict.js'
